
{'date': 'Mon Jun 27 2022 17:42:07.343 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 30
    Aventura().main()
AttributeError: 'Aventura' object has no attribute 'main'
'''},
{'date': 'Mon Jun 27 2022 17:42:53.297 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 32
    print(ADV[:100])
NameError: name 'ADV' is not defined
'''},
{'date': 'Mon Jun 27 2022 17:59:45.694 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 332
    Aventura().main(ADV)
  module <module> line 28
    i = "\n".join( ini for kind, ini in self.roteiro if kind == "I")
ValueError: need more than 1 value to unpack
'''},
{'date': 'Mon Jun 27 2022 18:14:27.910 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 34
  if kind == "L"
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 27 2022 18:14:39.743 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 340
    Aventura().main(ADV)
  module <module> line 36
    locais[umlocal] = [cmd]
IndexError: list assignment index out of range
'''},
{'date': 'Mon Jun 27 2022 18:16:27.618 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 341
    Aventura().main(ADV)
  module <module> line 38
    locais[umlocal].append(cmd)
IndexError: list index out of range
'''},
{'date': 'Mon Jun 27 2022 18:38:23.831 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 344
    Aventura().main(ADV)
  module <module> line 34
    print([lc[o] for lc in locais])
NameError: name 'o' is not defined
'''},
{'date': 'Mon Jun 27 2022 21:52:25.84 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 20
  _, cmd = adv[0]]
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 27 2022 21:52:36.135 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  loc, desc = cmd.split(":)
                           ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Mon Jun 27 2022 21:52:47.975 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 352
    Aventura().main(ADV)
  module <module> line 40
    locais = [Cenario(rot[ini:fim]) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 22
    Cenario.CENA[loc] = self
AttributeError: 'Cenario' object has no attribute 'CENA'
'''},
{'date': 'Mon Jun 27 2022 21:53:15.267 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 352
    Aventura().main(ADV)
  module <module> line 42
    print([lc[0] for lc in locais])
AttributeError: 'Cenario' object has no attribute '__getitem__'
'''},
{'date': 'Mon Jun 27 2022 22:12:23.274 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 362
    Aventura().main(ADV)
  module <module> line 49
    locais = [Cenario(rot[ini:fim]) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 26
    self.objeto = [Objeto(rot[ini:fim]) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 35
    loc, self.descreve = cmd.split(":")
ValueError: need more than 1 value to unpack
'''},
{'date': 'Mon Jun 27 2022 23:05:33.903 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 384
    Aventura().main(ADV)
  module <module> line 71
    locais = [Cenario(rot[ini:fim]) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 28
    self.objeto = [Objeto(adv[ini:fim],self) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 41
    self.verbo = {adv[ini].split(":")[-2]:Verbo(adv[ini:fim], cenario) for ini,fim in zip(lro, lro[1:]+[len(adv)])}
AttributeError: 'list' object has no attribute 'split'
'''},