
{'date': 'Sat Nov 30 2019 10:35:06.222 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 64
    Elevador()
  module <module> line 22
    a = Texto(predio, "oi", foi=lambda op="YY": Texto(predio, f"escolheu {op}").vai(), A="ee", B="uu")
TypeError: 'module' object is not callable
'''},
{'date': 'Sat Nov 30 2019 11:23:33.428 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 13
  super().__init__(img=img, vai=vai, style=style, tit=tit, alt=alt, cena=cena,
  ^
IndentationError: unexpected indent
'''},
{'date': 'Sat Nov 30 2019 11:24:22.342 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 111
    Elevador()
  module <module> line 66
    self.cesta = Elemento(CESTA, x=300, y=100,w=180,h=180, cena=predio, vai=self.sobe_desce)
  module <module> line 15
    self.posicao_inicial, self.posicao_final = posicao_inicial, posicao_final
NameError: name 'posicao_inicial' is not defined
'''},
{'date': 'Sat Nov 30 2019 11:25:27.481 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 111
    Elevador()
  module <module> line 66
    self.cesta = Elemento(CESTA, x=300, y=100,w=180,h=180, cena=predio, vai=self.sobe_desce)
  module <module> line 15
    self.posicao_inicial, self.posicao_final = posicao_inicial, posicao_final
NameError: name 'posicao_inicial' is not defined
'''},
{'date': 'Sat Nov 30 2019 11:31:20.15 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 119
    Elevador()
  module <module> line 59
    self.cesta = Item(CESTA, dict(x=0, y=300), cena=predio, x=300, y=100,w=180,h=180)
  module <module> line 35
    self.posicao_inicial, self.posicao_final = posicao_inicial, posicao_final
NameError: name 'posicao_inicial' is not defined
'''},
{'date': 'Sat Nov 30 2019 11:34:19.80 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 119
    Elevador()
  module <module> line 59
    self.cesta = Item(CESTA, dict(x=0, y=300), cena=predio, x=300, y=100,w=180,h=180)
  module <module> line 37
    self.imagem = Elemento(imagem, vai=self.movimenta, **kwargs)
  module <module> line 15
    self.posicao_inicial, self.posicao_final = posicao_inicial, posicao_final
NameError: name 'posicao_inicial' is not defined
'''},